version: '{branch}-{build}'

environment:
  matrix:
    - platform: x64
      PYTHON: "C:\\Users\\Coen\\AppData\\Local\\Programs\\Python\\Python36"
      
install:
  - SET "PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
  - easy_install scons
  
build_script:
  - python --version
  - scons --version
  - cd build/Windows
  - scons
