language: java
notifications:
  email: false
jdk:
  - oraclejdk8
  - oraclejdk9
  - openjdk8
branches:
  only:
    - master
script:
  - mvn test -Pblargg-test -B
  - mvn test -Pmooneye-test -B
cache:
  directories:
    - $TRAVIS_BUILD_DIR/target
    - $HOME/.m2
